/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 tree3d.gltf --transform
Author: yonimantz (https://sketchfab.com/yonimantz09)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-tree-6d1aeea748f147789004bc03e1930d32
Title: Stylized Tree
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  
  const { nodes, materials } = useGLTF('/tree3d-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.oak_01_leafes_Mat001_0.geometry} material={materials['leafes_Mat.001']} />
        <mesh geometry={nodes.oak_01_leafes_Mat001_0_1.geometry} material={materials['leafes_Mat.001']} />
        <mesh geometry={nodes.oak_01001_trunk_Mat001_0.geometry} material={materials['trunk_Mat.001']} />
        <mesh geometry={nodes.oak_01001_trunk_Mat001_0_1.geometry} material={materials['trunk_Mat.001']} />
        <mesh geometry={nodes.oak_01001_trunk_Mat001_0_2.geometry} material={materials['trunk_Mat.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tree3d-transformed.glb')
